### ISSUE TITLE
Add NoMAD Login UserInputUI Payload Keys

### ISSUE THREAD

**Issue by ckostovny** [ProfileCreator/ProfileCreator#124]
the upcoming 1.3 release of NoMAD Login adds UserInputUI payload keys, see https://gitlab.com/orchardandgrove-oss/NoMADLogin-AD/blob/develop/ConfigSamples/NoLoUserInput%20Sample.mobileconfig for a sample from the devs. Trying to import this sample into ProfileCreator results in warning that UserInputUI key will not be exported and to open an issue here. Thanks

**Comment by erikberglund** [comment]
I have added the new settings mentioned in the readme, but I have not pushed them yet as the app is not released in 1.3 from what I can tell, I need to think about adding the version selection to profile creator so one can select the version their targeting so they get the correct settings.
![Skärmavbild 2019-03-26 kl  08 56 35](https://user-images.githubusercontent.com/1296345/54980139-4063ef00-4fa5-11e9-8380-ebf8775534ba.png)

**Comment by fridomac** [comment]
Thank you @erikberglund for adding these. I replaced my "handcrafted" Profile with a ProfileCreator-generated one, but found that the Pop-Ups stay white and can not be selected. Has anybody seen the same?

**Comment by erikberglund** [comment]
@fridomac Did that work in your handcrafted version but not in the one exported from ProfileCreator? If that is the case, could you post both the handcrafted mobileconfig and the profile creator mobileconfig here, and I can see if there are any differences that is an error in ProfileCreator.

**Comment by erikberglund** [comment]
@fridomac Ah, I see what the error is now. I based the config on the example file in the NoMAD Login repo. And there is a typo in that example file where the items is spelled with capital I. And by looking in the code, I can see that it's looking for lowercase i. I will make an update to the manifest so you can check for manifest updates within 5 minutes. Ill post here when it's changed.

**Comment by erikberglund** [comment]
Now it's done. Go to Preferences -> Payloads and click "Check Now" and then "Download" to get the updated manifest. Then you can export the profile again and it should recognise the items.

I should add a fix to the nomad repo too as their example is incorrect.

**Comment by fridomac** [comment]
Thank you for catching that so fast Erik, tried it, imported into Jamf, deployed a machine, now works the same as the handcrafted one.

Greetings from sunny Nuremberg,
Frido.

**Comment by fridomac** [comment]
Ok, I have to reopen this: Even if the "items" is in lowercase, I still get the empty Pop-ups (sorry, had the wrong profile in Jamf for the last test). Will investigate further and report back here...
Bye, Frido.

**Comment by erikberglund** [comment]
@fridomac Ok. If you want you can post the profiles here, just drag them in the comment window and I can look at it too.

**Comment by fridomac** [comment]
Ok, I nailed it down to some umlauts in the items Fields, started working as soon as I changed them. Why they worked in the handmade profile escapes me, though. But I think you can close the issue for now. 
Thanks again for the support!
