### ISSUE TITLE
New keys for Microsoft Remote Desktop v10

### ISSUE THREAD

**Issue by patgmac** [ProfileCreator/ProfileCreator#158]
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/mac-whatsnew

> Support for all possible values of the "EnableCredSspSupport" and "Authentication Level" RDP file settings if the ClientSettings.EnforceCredSSPSupport user default key (in the com.microsoft.rdc.macos domain) is set to 0.

This setting allowed v10 to work with our privileged access system CyberArk, which previously was only known to work with v8 (deprecated). 

com.microsoft.rdc.macos ClientSettings.EnforceCredSSPSupport 0

**Comment by erikberglund** [comment]
Thank you, and sorry for the delay.

I have added the ClientSettings.EnforceCredSSPSupport as an integer.

Were there more keys that needed to be added to the manifest?

**Comment by apizz** [comment]
@patgmac just following up to make sure nothing additional needs to be added so we can close this.

**Comment by patgmac** [comment]
Thanks @apizz and @erikberglund. Being that there's only one possible value that can be entered for this key, is there a need to have it as a field in the UI requiring someone know to enter "0"? Seems a checkbox to enable would suffice. Unless I missed some documentation somewhere.

**Comment by kevinmcox** [comment]
@patgmac I've got an update that will only give the option for `0` and nothing else. But before I PR it can you confirm that `0` as an integer works for the setting?

**Comment by kevinmcox** [comment]
Thanks for the confirmation in Slack on this one @patgmac. The updated manifest was just merged.
