### ISSUE TITLE
More than one Payload per profile

### ISSUE THREAD

**Issue by kylejericson** [ProfileCreator/ProfileCreator#161]
Not sure if this is a bug or feature. If I build a profile with more than one payload. Which I normally would, but for Office 365 it makes sense. It seems to only save one part of my profile.
Example:
I created a profile with 6 payloads (not including the general payload) for each Office 365 app and it only saves on app config. So only com.microsoft.excel is saved in the profile. This is in version 0.3.0 of Profile Creator.

**Comment by erikberglund** [comment]
In what context do you mean save? Is it in the app where if you close the profile and reopen it in the app the payloads are not in the profile area above the library?

Or is it when exporting that only one of the payloads are included in the mobileconfig?

**Comment by erikberglund** [comment]
Could you right-click the profile you are talking about in the main window and select show in finder and drag and drop the file it highlights in the finder here?

![Screenshot 2019-05-17 at 22 45 14](https://user-images.githubusercontent.com/1296345/57955217-8ed2a180-78f5-11e9-8137-db0f11c8e0a1.png)

Then I can se what you are seeing.

**Comment by kylejericson** [comment]
It’s when I export the profile either as a profile or MCX.

**Comment by kylejericson** [comment]
[Test-M.mobileconfig.zip](https://github.com/erikberglund/ProfileCreator/files/3193538/Test-M.mobileconfig.zip)
Seems the MCX is broken when exporting.

**Comment by erikberglund** [comment]
Yes, more than one payload will be ignored in this version, weird as that is one of my tests that did not fail. I am investigating if there are some circumstances that makes it like this. Will put a fix out as soon as I fixed it.

**Comment by erikberglund** [comment]
OK, I have found and fixed this. I will put an updated version out tonight, have a few other things to do first, and want to see if there are any other things not working too before I put it up.

**Comment by erikberglund** [comment]
@kylejericson I have hopefully fixed this now with the 0.3.1 release. Please test and see if it works for you I that version.

**Comment by apizz** [comment]
@kylejericson can you please confirm that this is resolved?

**Comment by kylejericson** [comment]
@apizz So sorry thought I had already closed this. Yes this is fixed.

**Comment by apizz** [comment]
Thank you
