### ISSUE TITLE
Ability to add multiple fonts at once

### ISSUE THREAD

**Issue by alexrobert** [ProfileCreator/ProfileCreator#162]
We sometimes have projects that require us to add 30-50 fonts to Macs. Unfortunately having to add each font one by one makes us use different approaches. Would love to leverage MDM Profiles, but would require multi font drag and drop.

**Comment by apizz** [comment]
@alexrobert what does your 30-50 fonts equate to in terms of MB?

**Comment by erikberglund** [comment]
I think this is a valid feature, I have now made some code changes and tested this and it works nicely. I will include it in my next version. The only issue is that the app doesn't handle that many payloads very well. So I need to fix the tab view as well. AND the issue where multiple payloads sometimes are ignored when exporting, which must be fixed first.

**Comment by erikberglund** [comment]
This features is now available in the 0.3.1 version.

I did not have the time to finish the tab view, it's now a vertical scroll view but you don't see any indication of that so you have to shift scroll while hovering over a tab to show tabs that are hidden. For the next proper release I'll do something about that.

So, just click add and select all fonts you want to include.

And as I said, both the name of the tabs and an indication of the scrolling will be added in a future version.
