### ISSUE TITLE
Ability to add and sort in the Dock payload  

### ISSUE THREAD

**Issue by ivonesh** [ProfileCreator/ProfileCreator#165]
When adding an app or changing the order in the Dock payload `Static Apps` or `Static Others` section, you are currently unable to insert an item before, after, or between an existing item. When clicking the plus, you are given an additional line at the bottom of the list. You can enter the item, but it stays at the bottom of the list. There is no ability to drag to reorder. To insert a new app between other apps, you need to cut and paste to move all the items down.

Discussed here:
https://macadmins.slack.com/archives/C2N7MED7G/p1559589950032400

<img width="913" alt="Dock Payload" src="https://user-images.githubusercontent.com/1063950/58965139-b50d9380-8775-11e9-8c3d-f052c219701f.png">

**Comment by bsom** [comment]
+1 :-)

**Comment by ivonesh** [comment]
This was fixed in an update. I just confirmed it works in Version 0.3.2 (201907171032).
