### ISSUE TITLE
Broken payload on mjoave 10.14.5? Allowed Media

### ISSUE THREAD

**Issue by etphones** [ProfileCreator/ProfileCreator#166]
Was testing out denying external disk mounting payload which was successful on Mojave 10.14.1 tried the same on payload on 10.14.5 but will allow any type of external media to go through

**Comment by apizz** [comment]
@etphones can you confirm if you have any other profiles that use the `com.apple.systemuiserver` domain?  If it worked before but isn't working now, I'm wondering if there is a conflict between profiles

**Comment by erikberglund** [comment]
@etphones So, just to confirm.

The exact same .mobileconfig works in 10.14.1, but not in 10.14.5?

**Comment by etphones** [comment]
@apizz Cannot confirm if any other profiles use com.apple.systemuiserver domain at this moment.

@erikberglund getting odd behavior, i don't believe it is a 10.14.5 issue anymore. I only have two machines in production and moved both to 10.14.5. Both have the same profile configurations but only one is have this issue. Any insight would be helpful

**Comment by apizz** [comment]
@etphones any updates here?  Can you confirm you don't have profiles with duplicate or different payloads that are potentially conflicting?

**Comment by etphones** [comment]
@apizz i was able to locally install the profile to get it working and left it as is for the time being. There are no duplicate payload that are conflicting. I will be testing these configs with another machine soon.

**Comment by etphones** [comment]
After setting up a few more Macbooks I believe I found the "cause."

Allowed Media is a user profile and only applies to the user account that was initially enrolled into my MDM server. This configuration does not apply to all user accounts.
