### ISSUE TITLE
Profile name default value in new profile

### ISSUE THREAD

**Issue by ygini** [ProfileCreator/ProfileCreator#17]
The default profile name displayed when creating a new profile should be displayed as a placeholder instead of a real content.

(plus instead of "Untitled Profile..." it should be "Untitled Profile…" since … is a specific char and not just three dot)

**Comment by erikberglund** [comment]
I removed the default name completely, and when creating a new profile that field will always be selected first. And if no name is set, user will be promted when saving to choose a name.

**Comment by erikberglund** [comment]
Closing because of rewrite. These issues will have to be created again if they appear.
