### ISSUE TITLE
Firefox EnterprisePoliciesEnabled

### ISSUE THREAD

**Issue by gskibum** [ProfileCreator/ProfileCreator#171]
The Firefox payload has this statement:

> macOS defaults takes precedence over JSON policies (an alternative method to manage Firefox preferences). This preference must be set to true in macOS defaults in order to manage Firefox preferences through macOS defaults (configuration profile, plist, etc.). Once this value is set to true, JSON policies set through a policies.json config file (e.g. /Applications/Firefox.app/Contents/Resources/distribution/policies.json) are disabled even if no other policies are set in macOS defaults (this configuration profile).

However I am lost as to where to set this value.

**Comment by apizz** [comment]
@gskibum This should be at the top of the Firefox payload
![Screen Shot 2019-07-01 at 9 21 24 AM](https://user-images.githubusercontent.com/11789931/60439905-a635c780-9be1-11e9-9524-decbdb6a65bf.png)

**Comment by gskibum** [comment]
Oh it seems I'm confused. I have that checked and enabled, but the overall payload is not working.

I was thinking there was another defaults command I needed to get the rest working.

I'll dig in to that now that I know there isn't a defaults write command I need to set.

Thank you.

**Comment by gskibum** [comment]
It's working now. The process is a bit odd to get these payloads working in JAMF.

But I'm now off to the races and ProfileCreator will make my life much easier!

**Comment by apizz** [comment]
Glad to hear 🍻
