### ISSUE TITLE
New Office AutoUpdate Option

### ISSUE THREAD

**Issue by arajdon** [ProfileCreator/ProfileCreator#178]
Please see: https://www.kevinmcox.com/2019/07/disabling-microsoft-autoupdate-required-data-notice-in-managed-environments/

<key>AcknowledgedDataCollectionPolicy</key>
<string>RequiredDataOnly</string>

**Comment by apizz** [comment]
@arajdon This was already added by @kevinmcox per https://github.com/ProfileCreator/ProfileManifests/pull/106.  You may need to quit and reopen ProfileCreator to see this preference at the top.

![Screen Shot 2019-07-25 at 7 52 51 AM](https://user-images.githubusercontent.com/11789931/61872365-1f5ace80-aeb1-11e9-8443-978ce05e3a64.png)

**Comment by kevinmcox** [comment]
I’ll be working to add the new forced update options today and tomorrow as well.

**Comment by arajdon** [comment]
> @arajdon This was already added by @kevinmcox per [ProfileCreator/ProfileManifests#106](https://github.com/ProfileCreator/ProfileManifests/pull/106). You may need to quit and reopen ProfileCreator to see this preference at the top.
> 
> ![Screen Shot 2019-07-25 at 7 52 51 AM](https://user-images.githubusercontent.com/11789931/61872365-1f5ace80-aeb1-11e9-8443-978ce05e3a64.png)

You're right. I've found the option after reopening ProfileCreator.

Thanks. 👍
