### ISSUE TITLE
Contribute 

### ISSUE THREAD

**Issue by kylejericson** [ProfileCreator/ProfileCreator#179]
I would love to help contribute with this; maybe a tester as I use this daily.

**Comment by kevinmcox** [comment]
Additional help is always appreciated. One aspect that needs constant work are the Profile Manifests: https://github.com/ProfileCreator/ProfileManifests  There are always updates that need to be added or new manifests created.

`#profilecreator-dev` in the MacAdmins Slack is a great place for discussion.
