### ISSUE TITLE
Saving profiles locally and using a signing identity doesn't sign the profile

### ISSUE THREAD

**Issue by bartreardon** [ProfileCreator/ProfileCreator#183]
as per the title - When I create a profile in PPPC 1.1.0 and save it locally, selecting a signing identity doesn't appear to sign the profile.

**Comment by kevinmcox** [comment]
Hey Bart, sounds like you're looking for Jamf's PPPC Utility: https://github.com/jamf/PPPC-Utility

**Comment by bartreardon** [comment]
oh crap....wrong github window.....dang :/

**Comment by kevinmcox** [comment]
No worries!

**Comment by bartreardon** [comment]
derp
