### ISSUE TITLE
UI glitch when playing with bouncing scrollview

### ISSUE THREAD

**Issue by ygini** [ProfileCreator/ProfileCreator#19]
Look the attached video, when playing with the bouncing scroll view we see a previous view behind.

[UI bug.zip](https://github.com/ProfileCreator/ProfileCreator/files/332279/UI.bug.zip)

**Comment by erikberglund** [comment]
Fixed in my testing. The scroll view didn't draw a background. Also fixed grey fields that showed up when "bouncing" by adding a background color to the TableView as well.

**Comment by ygini** [comment]
IMHO the fix isn't to add a background but to avoid stacking different view.

For the scenario you've, you should use NSTabView with tabless options to handle the move from one kind of content to another if you don't want to manage the add and remove by yourself.

**Comment by erikberglund** [comment]
Thank you. Yeah, I totally agree, that is a much better solution. I haven't considered that before, but will add it to my list of things to fix!

**Comment by erikberglund** [comment]
Added that code now actually, to test this approach and it worked fine. So now, that is the fix :)

**Comment by erikberglund** [comment]
Closing because of rewrite. These issues will have to be created again if they appear.
