### ISSUE TITLE
Password entry for profile signing doesn't work

### ISSUE THREAD

**Issue by cubednet135** [ProfileCreator/ProfileCreator#190]
When I try to sign a profile, it doesn't let me enter my password in the Always Allow/Deny/Allow authentication box.

**Comment by jmahlman** [comment]
I am having the same issue. 

Workaround for anyone who doesn't know:

- Get all of your code signing certs: /usr/bin/security find-identity -p codesigning -v
- Sign profile: /usr/bin/security cms -S -N "Name Of Cert" -i /path/to/your.mobileconfig -o /path/to/your/signed/output.mobileconfig

**Comment by apizz** [comment]
I assume this is a 10.15 issue, as I'm on 10.14.6 and sign all our profiles.  Until we get a new dev working on this app, I'm afraid there's no ETA on a resolution.
