### ISSUE TITLE
NoMAD Login: Textfields for Popups not editable

### ISSUE THREAD

**Issue by fridomac** [ProfileCreator/ProfileCreator#194]
I can´t edit the Textfields when adding a NoMAD Login Payload, select the "UserInput" card and add a Popup or a Text Input Field. Only the Title can be edited.

Bye, Frido.

**Comment by apizz** [comment]
@fridomac You have to right-click on the field when there's more than one.

![Screen Shot 2020-01-20 at 11 16 27 AM](https://user-images.githubusercontent.com/11789931/72741778-549d5c00-3b76-11ea-8986-16bec6eb1f51.png)

**Comment by fridomac** [comment]
Thank you, could have thought of that myself, sorry!

**Comment by apizz** [comment]
No worries. Sorry for the delay

**Comment by fridomac** [comment]
Sorry to open this up again: I tried it again today, the right-click-method works for text Fields, but not for Popups :-( (at least not for me)

Bye,Frido.
