### ISSUE TITLE
Microsoft Edge Payload Not Functioning

### ISSUE THREAD

**Issue by flmacadmin** [ProfileCreator/ProfileCreator#201]
It appears there is a typo in the preference domain for the Microsoft Edge payload. It is written as "com.microsoft.Edgee". Removing the extra "e" from the the preference domain in the plist file (after converting from .mobileconfig to plist) resolves the issue.

**Comment by apizz** [comment]
Hi, yes we identified this a couple days ago, thanks for reporting.

Going to merge this PR (https://github.com/ProfileCreator/ProfileManifests/pull/214) today to resolve it and add some things that were missed.

**Comment by apizz** [comment]
Try quitting and reopening PC.  Should get the updated manifest for Edge.
