### ISSUE TITLE
AirPrint payload - PC only accepts IP addresses for IPAddress key

### ISSUE THREAD

**Issue by Coros** [ProfileCreator/ProfileCreator#202]
I understand the IPAddress key seems literal but Apple Configurator allows you enter hostname or IP address in this key.  iOS/iPadOS does properly work with hostnames in this key.  

<img width="788" alt="Screen Shot 2020-01-23 at 9 34 59 AM" src="https://user-images.githubusercontent.com/17457045/72998565-ad156900-3dc3-11ea-8e4b-ef776dfd3467.png">

**Comment by apizz** [comment]
Thanks for reporting this. Will update this soon

**Comment by apizz** [comment]
Fixed
