### ISSUE TITLE
Feature Request: Add profile for Finder:Show All File Extensions

### ISSUE THREAD

**Issue by FritzX6** [ProfileCreator/ProfileCreator#216]
### What is being requested?
A new profile for the following preference: *Show all filename extensions*
![image](https://user-images.githubusercontent.com/931724/89201185-1a7a3180-d57f-11ea-8329-34ee6cab4990.png)

### Where is this value stored?
```
~/Library/Preferences/.GlobalPreferences.plist
<key>AppleShowAllExtensions</key>
	<true/>
```

### Per this conversation in macadmins Slack:
![image](https://user-images.githubusercontent.com/931724/89200484-14378580-d57e-11ea-9bfa-8a84bed8cc04.png)

### Why is this important?
Malicious downloads will often be named in a way that appears innocuous to disguise its intent. For instance a file could be named `Quarterly-Report.pdf.pkg` the file is technically an executable but because file extensions are hidden it will appear to be a simple pdf file. By forcing the operating system to show all file extensions you are less likely to run a piece of malicious software unintentionally.

**Comment by apizz** [comment]
Thanks for this, and it addresses a good point. Yikes, 8 months ago and no one put in an issue or PR ... Will definitely get this added.

In future, this repo is meant more for the ProfileCreator app itself while the ProfileManifests repo is for additions / changes to the payloads & preferences themselves.

**Comment by apizz** [comment]
@FritzX6 please quit & reopen ProfileCreator to get the latest manifest with the addition
