### ISSUE TITLE
v0.3.2-201907171032-beta crash on Big Sur beta 4 directly on startup

### ISSUE THREAD

**Issue by meta-github** [ProfileCreator/ProfileCreator#217]
It crashes on start:

$ /Applications/ProfileCreator.app/Contents/MacOS/ProfileCreator 
2020-08-06 00:39:46.057 ProfileCreator[80080:2395739] *** Assertion failure in -[ProfileCreator.MainWindowOutlineView _safeSendDelegateHeightOfRow:], NSTableView.m:1639
2020-08-06 00:39:46.061 ProfileCreator[80080:2395739] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSTableView variable rowHeight error: The value must be > 0 for row 0, but the delegate <ProfileCreator.MainWindowOutlineViewController: 0x7fbb3452cfb0> gave 0.000.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2a02c05f __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff6a0aa6f4 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2a054c36 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff2ca57489 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   AppKit                              0x00007fff26ee7efe -[NSTableView _safeSendDelegateHeightOfRow:] + 293
	5   AppKit                              0x00007fff26ee7d29 -[NSTableView _uncachedRectHeightOfRow:] + 273
	6   AppKit                              0x00007fff276ff4fc -[_NSTableRowHeightStorage _cacheRowSpansInRange:] + 108
	7   AppKit                              0x00007fff276ff65a -[_NSTableRowHeightStorage _ensureRowSpansStorage] + 137
	8   AppKit                              0x00007fff26ed9bcb -[_NSTableRowHeightStorage computeTableHeightForNumberOfRows:] + 98
	9   AppKit                              0x00007fff26ed9647 -[NSTableView _minimumFrameSize] + 66
	10  AppKit                              0x00007fff26ee630e -[NSTableView tile] + 130
	11  AppKit                              0x00007fff26ed94ed -[NSTableView frame] + 102
	12  AppKit                              0x00007fff26ebdacf -[NSClipView _reflectDocumentViewFrameChange] + 55
	13  AppKit                              0x00007fff26e7c3a4 -[NSView _postFrameChangeNotification] + 82
	14  AppKit                              0x00007fff26e750c7 -[NSView setFrameSize:] + 2344
	15  AppKit                              0x00007fff26ee8c04 -[NSTableView setFrameSize:] + 254
	16  AppKit                              0x00007fff26ee8afa -[NSOutlineView setFrameSize:] + 260
	17  AppKit                              0x00007fff26ee6007 -[NSTableView _tileAndRedisplayAll] + 172
	18  AppKit                              0x00007fff26f7cc91 -[NSOutlineView reloadData] + 522
	19  ProfileCreator                      0x000000010388bafc ProfileCreator + 162556
	20  ProfileCreator                      0x000000010388b46d ProfileCreator + 160877
	21  ProfileCreator                      0x000000010388b5df ProfileCreator + 161247
	22  ProfileCreator                      0x0000000103987385 ProfileCreator + 1192837
	23  ProfileCreator                      0x00000001039881a3 ProfileCreator + 1196451
	24  ProfileCreator                      0x00000001039856ac ProfileCreator + 1185452
	25  ProfileCreator                      0x0000000103985bff ProfileCreator + 1186815
	26  ProfileCreator                      0x000000010397e781 ProfileCreator + 1156993
	27  ProfileCreator                      0x000000010397e80f ProfileCreator + 1157135
	28  AppKit                              0x00007fff26e9fa9e -[NSClassSwapper initWithCoder:] + 1125
	29  Foundation                          0x00007fff2c936249 _decodeObjectBinary + 2766
	30  Foundation                          0x00007fff2c935653 _decodeObject + 152
	31  Foundation                          0x00007fff2c93553e -[NSKeyedUnarchiver decodeObjectForKey:] + 162
	32  AppKit                              0x00007fff26e14fb1 -[NSNibConnector initWithCoder:] + 97
	33  AppKit                              0x00007fff26e14eec -[NSNibOutletConnector initWithCoder:] + 404
	34  Foundation                          0x00007fff2c936249 _decodeObjectBinary + 2766
	35  Foundation                          0x00007fff2c937ce7 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 848
	36  Foundation                          0x00007fff2c94ffac -[NSArray(NSArray) initWithCoder:] + 161
	37  Foundation                          0x00007fff2c936249 _decodeObjectBinary + 2766
	38  Foundation                          0x00007fff2c935653 _decodeObject + 152
	39  Foundation                          0x00007fff2c93553e -[NSKeyedUnarchiver decodeObjectForKey:] + 162
	40  AppKit                              0x00007fff26e13be4 -[NSIBObjectData initWithCoder:] + 168
	41  Foundation                          0x00007fff2c936249 _decodeObjectBinary + 2766
	42  Foundation                          0x00007fff2c935653 _decodeObject + 152
	43  Foundation                          0x00007fff2c93553e -[NSKeyedUnarchiver decodeObjectForKey:] + 162
	44  AppKit                              0x00007fff26e9e6ae -[NSNib _instantiateNibWithExternalNameTable:options:] + 512
	45  AppKit                              0x00007fff26e9e3b9 -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
	46  AppKit                              0x00007fff2762ed2e -[NSStoryboard _instantiateMainMenu:] + 189
	47  AppKit                              0x00007fff26e051bc NSApplicationMain + 712
	48  ProfileCreator                      0x0000000103868999 ProfileCreator + 18841
	49  libdyld.dylib                       0x00007fff6b321851 start + 1
	50  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

$ sw_vers 
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5343i

**Comment by apizz** [comment]
Thanks for the report.  There's no one who's been able to take over the app project, so for now you'll have to use ProfileCreator on a Mac or VM running 10.12 - 10.15.

**Comment by apizz** [comment]
To be clear, was this the same behavior on earlier betas?
