### ISSUE TITLE
Request: Add Enterprise option for WiFi encryption types

### ISSUE THREAD

**Issue by PhillyPhoto** [ProfileCreator/ProfileCreator#220]
When adding a WiFi network, you have the option of choosing None, WEP, WPA/WPA2, WPA2, WPA3, or Any. There should be an option to use WPA2 Enterprise and the like for 802.1x encryption. This is available through Jamf and Apple Configurator 2.

**Comment by apizz** [comment]
So it you look at the actual XML, there is no difference as far as the key value is concerned between any of the personal vs enterprise WPA values (`EncryptionType`). From Apple Configurator 2:

<img width="299" alt="Screen Shot 2020-10-24 at 9 09 07 PM" src="https://user-images.githubusercontent.com/11789931/97096654-3f8db600-163d-11eb-98a4-000f50dd7805.png">

The actual XML values are all WPA, WPA2, WPA3, and why in ProfileCreator we don't distinguish between Personal vs. Enterprise in the options.  The only difference functionally for WPA2 Enterprise, for example, are the keys that are the options graphically presented.  Example screenshots from AC2 below:

**WPA2 Personal**
<img width="926" alt="Screen Shot 2020-10-24 at 9 10 51 PM" src="https://user-images.githubusercontent.com/11789931/97096667-6ea42780-163d-11eb-8c72-c429a2512735.png">

**WPA2 Enterprise**
<img width="926" alt="Screen Shot 2020-10-24 at 9 10 46 PM" src="https://user-images.githubusercontent.com/11789931/97096669-72d04500-163d-11eb-9d25-6b53a534a15d.png">

All of the keys listed in Apple's documentation (https://developer.apple.com/documentation/devicemanagement/wifi) are present in ProfileCreator's Wi-Fi manifest.

So I guess my question to you is what do you really want here?  Is it that you want comfort in knowing that the option you select matches what's in Jamf/AC2, or more that if you select X option that all the related keys are added graphically in a similar fashion as Jamf/AC2?
