### ISSUE TITLE
Crash at launching ProfileCreator

### ISSUE THREAD

**Issue by rhit-admin** [ProfileCreator/ProfileCreator#224]
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

More Information: see attached crashlog

[crashlog.txt](https://github.com/ProfileCreator/ProfileCreator/files/5413649/crashlog.txt)

**Comment by apizz** [comment]
Duplicate of #217. Please grab the currently unreleased 0.3.3 version from the #profilecreator MacAdmins Slack channel: https://macadmins.slack.com/archives/C2N7MED7G/p1600361509043000
