### ISSUE TITLE
Big Sur issue

### ISSUE THREAD

**Issue by rossoneris** [ProfileCreator/ProfileCreator#231]
Seems profilecreator does not work with Big Sur

**Comment by kevinmcox** [comment]
There is a beta version available in the #profilecreator channel on the MacAdmins Slack that works on Big Sur.

**Comment by apizz** [comment]
Duplicate of #217. Please grab the currently unreleased 0.3.3 version from the #profilecreator MacAdmins Slack channel: https://macadmins.slack.com/archives/C2N7MED7G/p1600361509043000

**Comment by danrabinowitz** [comment]
Any ETA of when 0.3.3 will be released?

**Comment by kevinmcox** [comment]
Discussions are on-going in Slack. We're trying to work out an issue related to signing and notarization.
