### ISSUE TITLE
Crashes at launch on macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by vasquesbc** [ProfileCreator/ProfileCreator#232]
The App crashes immediately after launching on macOS 11.0 Big Sur
See attached crash log for details.

[ProfileCreator_2020-11-23-095100_thehive.log](https://github.com/ProfileCreator/ProfileCreator/files/5581809/ProfileCreator_2020-11-23-095100_thehive.log)

**Comment by walkintom** [comment]
There's a compatible version uploaded to the Macadmins Slack channel:
https://macadmins.slack.com/archives/C2N7MED7G/p1600357069037500
https://macadmins.slack.com/files/U0EG5CN7J/F01AFNXRLG7/profilecreator-v0.3.3-unsigned.zip
