### ISSUE TITLE
Mac big sur fail to run

### ISSUE THREAD

**Issue by weiloon1234** [ProfileCreator/ProfileCreator#235]
tried:
v0.3.1 and v0.3.2

macOS Big Sur Version 11.1

attach error log
[profilecreator.zip](https://github.com/ProfileCreator/ProfileCreator/files/5707510/profilecreator.zip)

**Comment by kevinmcox** [comment]
There is a compatible version on the MacAdmins Slack:
https://macadmins.slack.com/files/U0EG5CN7J/F01AFNXRLG7/profilecreator-v0.3.3-unsigned.zip

**Comment by JoaoSobral** [comment]
Hi,

I don't have an account on macadmin.slack.com. Is it possible to attach it here?

Thanks 
Pedro

**Comment by roodavis** [comment]
Go to https://macadmins.slack.com and create an account. It will be the best thing you do today.

**Comment by stvnmbr1** [comment]
can i get an invitation?

**Comment by apizz** [comment]
@stvnmbr1 https://www.macadmins.org/
