### ISSUE TITLE
Allowed Media trying to block USB ports on MacOs 

### ISSUE THREAD

**Issue by Mghannaj** [ProfileCreator/ProfileCreator#241]
Hello guys, 

Greetings. I was trying to block USB ports on Mac devices using the below XML code. did I make it correctly or do I missed something up. 

<img width="799" alt="BlockUSB" src="https://user-images.githubusercontent.com/7113443/110940729-69bfe600-8348-11eb-831c-e01675994fb1.png">
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadDisplayName</key>
			<string>Allowed Media</string>
			<key>PayloadIdentifier</key>
			<string>com.github.erikberglund.ProfileCreator.7C3E7C1F-7954-42DA-8E38-94AB2FE1EB0D.com.apple.systemuiserver.12AE044A-FAEF-4AEB-8A48-EDDA36E4B31B</string>
			<key>PayloadOrganization</key>
			<string></string>
			<key>PayloadType</key>
			<string>com.apple.systemuiserver</string>
			<key>PayloadUUID</key>
			<string>12AE044A-FAEF-4AEB-8A48-EDDA36E4B31B</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDisplayName</key>
	<string>BlockUSB</string>
	<key>PayloadIdentifier</key>
	<string>com.github.erikberglund.ProfileCreator.7C3E7C1F-7954-42DA-8E38-94AB2FE1EB0D</string>
	<key>PayloadOrganization</key>
	<string>XYZ</string>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>7C3E7C1F-7954-42DA-8E38-94AB2FE1EB0D</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
`

**Comment by apizz** [comment]
So what you've shown here is the GUI setting you've enabled and the XML content from what I assume you copied and pasted from the XML section?  When you ask "did I make it correctly", are you creating a profile?  Exporting as a plist (check the applicable wiki pages for these)?

Looking at Apple's documentation from the payload (https://developer.apple.com/documentation/devicemanagement/mediamanagementallowedmedia) it appears this was deprecated in macOS 11.0, so if you're trying to use this on Big Sur that could be the issue.

I'll file an issue to have that updated.

**Comment by Mghannaj** [comment]
Hi @apizz thank you for the comment. 

Yes, I am creating a profile to manage the organization Mac devices and then I will upload it as a custom profile into Intune. By the way versions of our Mac is totally compatible with Profile Creator. 

What I understood is that blocking USB in Mac devices are not supported any more?

**Comment by apizz** [comment]
Per the linked Apple documentation in prev. response (https://developer.apple.com/documentation/devicemanagement/mediamanagementallowedmedia) Apple has deprecated this profile payload in macOS 11.0+.  While it _may_ continue to work, Apple deprecating it indicates that at some point it will no longer work.

**Comment by apizz** [comment]
Since the original question is "am I doing this right", I'm going to close this issue since with Ventura this is no longer a support manifest in the last 3 major macOS versions
