### ISSUE TITLE
11.5.1 - uncaught exception of type NSException with PC_v0.3.2

### ISSUE THREAD

**Issue by imanassypov** [ProfileCreator/ProfileCreator#247]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSTableView variable rowHeight error: The value must be > 0 for row 0, but the delegate <ProfileCreator.MainWindowOutlineViewController: 0x600001dfcbd0> gave 0.000.'
abort() called
terminating with uncaught exception of type NSException

**Comment by apizz** [comment]
Please use latest release
