### ISSUE TITLE
Feature Request: Auto-naming PayloadIdentifier via OrganizationIdentifier + PayloadDisplayName

### ISSUE THREAD

**Issue by ivonesh** [ProfileCreator/ProfileCreator#55]
In `Profile Creator`>`Preferences`>`Profile Defaults`, I am able to set my `Organization Identifier` `com.company` which auto-fills `PayloadIdentifer` on the `General` portion of a new profile with `com.company.UUID`. 

For my usage, I delete the `UUID` and mimic the `PayloadDisplayName` in lowercase and separated by underscores. This allows easy identification when calling the list of profiles installed on a machine via Terminal versus having to open `System Preferences`>`Profiles`. 

Would it be possible to have a setting that allows the `PayloadDisplayName` to auto-fill/append instead of the `UUID`? 

Or, if that is too difficult to implement, a setting that would allow the `UUID` to not be automatically appended to the `PayloadIdentifier`.

<img width="913" alt="screen shot 2018-08-28 at 1 58 30 pm" src="https://user-images.githubusercontent.com/1063950/44744380-a6999980-aaca-11e8-86e4-fb3760b8e6b7.png">

**Comment by ivonesh** [comment]
Thanks for the detailed response. Should I close this issue?

**Comment by erikberglund** [comment]
No leavw it until its implemented

**Comment by erikberglund** [comment]
@ivonesh The next release will allow you to create your own payload identifier format string. I should add display name as a variable to use.

**Comment by erikberglund** [comment]
Or better yet, allow a keyPath to any key in the payload.

**Comment by ivonesh** [comment]
Sounds great!

**Comment by erikberglund** [comment]
I've added the code for the PayloadDisplayName, but currently it only uses the default value as this is set when the payload first is added or when the payload first shows the xml view (as that technically is an internal export).

Her is the wiki info about this upcoming feature: https://github.com/erikberglund/ProfileCreator/wiki/Preferences:-Advanced#payloadidentifier-format

If you want this to be the current value when exporting, we should probably open a new issue specific to that so it's easier for me to track.

**Comment by apizz** [comment]
This looks to have been implemented in https://github.com/ProfileCreator/ProfileCreator/releases/tag/v0.2.5-beta.10
